create view DETALLES_APUESTAS AS
select B.STATUS, B.FK_ID_PERSON, Q.ID, Q.QUOTA_1, Q.QUOTA_2, Q.QUOTA_3, C.NAME, Q.FK_ID_CATEGORY_BET, T.NAME_TEAM, M.FK_ID_TEAM_LOCAL, 
M.FK_ID_TEAM_VISIT
from Bet B
  inner join DETAIL_BET D on B.ID = D.FK_ID_BET
  inner join QUOTA_BET Q on Q.ID = D.FK_ID_QUOTA_BET
  inner join CATEGORY_BET C on  C.ID = Q.FK_ID_CATEGORY_BET
  inner join MATCH M on M.ID = Q.FK_ID_MATCH
  inner join TEAM T on M.FK_ID_TEAM_VISIT = T.ID OR M.FK_ID_TEAM_LOCAL = T.ID
  -- inner join TEAM T on M.FK_ID_TEAM_LOCAL = T.ID 
  where B.ID = 4;

select * from DETALLES_APUESTAS;