create or replace trigger APUESTA AFTER INSERT OR UPDATE OR DELETE on BET for each row  
begin    
  IF INSERTING THEN
     update PERSON 
     SET BALANCE_AVAILABLE = - :NEW.VALUE_BET + BALANCE_AVAILABLE
     where ID = :NEW.FK_ID_PERSON;     
  END IF;  
  
  IF UPDATING THEN   
    
    IF :NEW.VALUE_BET > :OLD.VALUE_BET THEN
      update PERSON 
      SET BALANCE_AVAILABLE = :NEW.VALUE_BET - :OLD.VALUE_BET + BALANCE_AVAILABLE
      where ID = :NEW.FK_ID_PERSON;     
    END IF;
    
    IF :NEW.VALUE_BET < :OLD.VALUE_BET THEN
      update PERSON
      SET BALANCE_AVAILABLE = :NEW.VALUE_BET - :OLD.VALUE_BET + BALANCE_AVAILABLE
      where ID = :NEW.FK_ID_PERSON;      
    END IF;
  END IF;
  
  IF DELETING THEN 
      update PERSON 
      SET BALANCE_AVAILABLE = - :OLD.VALUE_BET + BALANCE_AVAILABLE 
      where ID = :OLD.FK_ID_PERSON; 
   END IF;
end;