create or replace trigger DETALLE_APUESTA AFTER INSERT OR UPDATE ON detail_bet for each row
begin 

    IF INSERTING THEN
      UPDATE BET 
      SET TOTAL_EARNED =  (SELECT B.QUOTA_EARNED FROM QUOTA_BET B WHERE ID = :NEW.FK_ID_QUOTA_BET) * VALUE_BET
      WHERE ID = :NEW.FK_ID_BET;
    END IF;

    IF UPDATING THEN
      UPDATE BET 
      SET TOTAL_EARNED =  (SELECT B.QUOTA_EARNED FROM QUOTA_BET B WHERE ID = :NEW.FK_ID_QUOTA_BET) * VALUE_BET
      WHERE ID = :NEW.FK_ID_BET;
    END IF;
end;