CREATE OR REPLACE PROCEDURE CLOSE_SESSION_USER AS

 RESULT_AUX INTEGER := 0;
 AUX INTEGER := 0;
BEGIN
  FOR AUX IN 1 .. 50 LOOP
     RESULT_AUX := AUX * X;
     DBMS_OUTPUT.PUT_LINE(AUX || ' * ' ||  X || ' = ' || RESULT_AUX);
  END LOOP;
END; 
