update withdraw_requisite set fk_id_requisite = 5 where fk_id_requisite = 4;

ALTER TABLE LEGITTRIP.BET ADD CONSTRAINT FK_PERSON FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.BONUS_PERSON ADD CONSTRAINT FK_BONUS FOREIGN KEY (FK_ID_BONUS) REFERENCES LEGITTRIP.BONUS(ID);

ALTER TABLE LEGITTRIP.BONUS_PERSON ADD CONSTRAINT FK_PERSON_BONUS FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.DATA_FINANCIAL ADD CONSTRAINT FK_PERSONFINANCIAL FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.DEPOSIT ADD CONSTRAINT FK_PERSONDEPOSITE FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.DEPOSIT ADD CONSTRAINT FK_STATUS_DEPOSIT FOREIGN KEY (FK_ID_STATUS_DEPOSIT) REFERENCES LEGITTRIP.STATUS_DEPOSIT(ID);

ALTER TABLE LEGITTRIP.DEPOSIT ADD CONSTRAINT FK_TYPE_PAY FOREIGN KEY (FK_ID_MODE_PAY) REFERENCES LEGITTRIP.TYPE_PAY(ID);

ALTER TABLE LEGITTRIP.LIMIT_BET ADD CONSTRAINT FK_PERSON_LIMIT_BET FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.Match ADD CONSTRAINT FK_TEAMS_VISIT FOREIGN KEY (FK_ID_TEAM_VISIT) REFERENCES LEGITTRIP.TEAM(ID);

ALTER TABLE LEGITTRIP.Match ADD CONSTRAINT FK_TEAMS_LOCALS FOREIGN KEY (FK_ID_TEAM_LOCAL) REFERENCES LEGITTRIP.TEAM(ID);

ALTER TABLE LEGITTRIP.Match ADD CONSTRAINT FK_STATUS_MATCH FOREIGN KEY (FK_ID_STATUS_EVENT) REFERENCES LEGITTRIP.STATUS_MATCH(ID);

ALTER TABLE LEGITTRIP.PERSON ADD CONSTRAINT FK_MASTER_LOCATION_COUNTRY FOREIGN KEY (FK_ID_COUNTRY) REFERENCES LEGITTRIP.MASTER_LOCATION_COUNTRY(ID);

ALTER TABLE LEGITTRIP.PERSON ADD CONSTRAINT FK_MASTER_LOCATION_DEPARTAMENT FOREIGN KEY (FK_ID_DEPARTMENT) REFERENCES LEGITTRIP.MASTER_LOCATION_DEPARTAMENT(ID);

ALTER TABLE LEGITTRIP.PERSON ADD CONSTRAINT FK_MASTER_LOCATION_MUNICIPALITY FOREIGN KEY (FK_ID_MUNICIPALITY) REFERENCES LEGITTRIP.MASTER_LOCATION_MUNICIPALITY(ID);

ALTER TABLE LEGITTRIP.PHONE ADD CONSTRAINT FK_PERSON_PHONE FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.PREFERENCE ADD CONSTRAINT FK_PERSON_PREFERENCES FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.PREFERENCE ADD CONSTRAINT FK_LENGUAGE FOREIGN KEY (FK_ID_LANGUAGES_TO_EMAIL) REFERENCES LEGITTRIP.LENGUAGE(ID);

ALTER TABLE LEGITTRIP.PROOF_VERIFICATION_USER ADD CONSTRAINT FK_PERSON_PROOF_VERIFICATION FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.PROOF_VERIFICATION_USER ADD CONSTRAINT FK_STATUS_VERIFICATION FOREIGN KEY (FK_ID_STATUS_VERIFICATION) REFERENCES LEGITTRIP.STATUS_VERIFICATION(ID);

ALTER TABLE LEGITTRIP.WITHDRAW ADD CONSTRAINT FK_PERSON_RETIREMENT FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.WITHDRAW_REQUISITE ADD CONSTRAINT FK_REQUISITE_TO_WITHDRAW FOREIGN KEY (FK_ID_REQUISITE) REFERENCES LEGITTRIP.REQUISITE_TO_WITHDRAW(ID);

ALTER TABLE LEGITTRIP.WITHDRAW_REQUISITE ADD CONSTRAINT FK_Withdraw FOREIGN KEY (FK_ID_Withdraw) REFERENCES LEGITTRIP.Withdraw(ID);

ALTER TABLE LEGITTRIP.SESION ADD CONSTRAINT FK_PERSON_SESION FOREIGN KEY (FK_ID_PERSON) REFERENCES LEGITTRIP.PERSON(ID);

ALTER TABLE LEGITTRIP.QUOTA_BET ADD CONSTRAINT FK_CATEGORY_BET FOREIGN KEY (FK_ID_CATEGORY_BET) REFERENCES LEGITTRIP.QUOTA_BET (ID);

ALTER TABLE LEGITTRIP.QUOTA_BET ADD CONSTRAINT FK_MATCH_BET FOREIGN KEY (FK_ID_Match ) REFERENCES LEGITTRIP."MATCH"(ID);

ALTER TABLE LEGITTRIP.DETAIL_BET ADD CONSTRAINT FK_BET_ID FOREIGN KEY (FK_ID_BET) REFERENCES LEGITTRIP.BET (ID);

ALTER TABLE LEGITTRIP.DETAIL_BET ADD CONSTRAINT FK_QUOTA_BET FOREIGN KEY (FK_ID_QUOTA_BET) REFERENCES LEGITTRIP.QUOTA_BET (ID);

ALTER TABLE LEGITTRIP.ZONE_TIME_LOCATION_DEPARTAMEN ADD CONSTRAINT FK_MASTER_LOCATION_DEPARTAMENT_ZONE_TIME FOREIGN KEY (FK_ID_DEPARTAMENT) REFERENCES LEGITTRIP.MASTER_LOCATION_DEPARTAMENT(ID);

ALTER TABLE LEGITTRIP.ZONE_TIME_LOCATION_DEPARTAMEN ADD CONSTRAINT FK_MASTER_ZONE_TIME_DEPARTMENT FOREIGN KEY (FK_ID_ZONE_TIME) REFERENCES LEGITTRIP.MASTER_ZONE_TIME(ID);

update preference set limit_time_sesion = 5

update detail_bet set quota_bookmaker = (select 1 from quota_bet where quota_bet.quota_1 <> 0 and detail_bet.fk_id_quota_bet = quota_bet.id);

update detail_bet set quota_bookmaker = 2 where quota_bookmaker is null;
